/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pesanjaketlab;

import java.awt.Color;


/**
 *
 * @author ILHAM HADISYAH
 */
public class ParentPage extends javax.swing.JFrame {

    /**
     * Creates new form ParentPage
     */
    static String PageName ;
    public ParentPage() {
        initComponents();
        this.setTitle("Pesan Jaket Lab");
        
        
        setLocationRelativeTo(this);
        setExtendedState(ParentPage.MAXIMIZED_BOTH);
        AboutUsPane.setVisible(false);
        KeranjangPane.setVisible(false);
        PesanPane.setVisible(false);
        HomePane.setVisible(true);
        AboutUs.setBackground(Color.white);
        Keranjang.setBackground(Color.white);
        Pesan.setBackground(Color.white);
        Home.setBackground(new Color(0,153,0));
        HomeWord.setForeground(Color.black);
        PesanWord.setForeground(new Color(77, 77,77));
        KeranjangWord.setForeground(new Color(77, 77,77));
        AboutUsWord.setForeground(new Color(77, 77,77));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FullName = new javax.swing.JLabel();
        NIM = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        NoTelp = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        MainPane = new javax.swing.JPanel();
        HomePane = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        PesanPane = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        KeranjangPane = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        AboutUsPane = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        AboutUs = new javax.swing.JPanel();
        AboutUs1 = new javax.swing.JPanel();
        AboutUsWord = new javax.swing.JLabel();
        Keranjang = new javax.swing.JPanel();
        Keranjang1 = new javax.swing.JPanel();
        KeranjangWord = new javax.swing.JLabel();
        Pesan = new javax.swing.JPanel();
        Pesan1 = new javax.swing.JPanel();
        PesanWord = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        Home1 = new javax.swing.JPanel();
        HomeWord = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(99, 167, 157, 205);

        jLabel1.setText("Full Name");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(60, 426, 60, 14);

        jLabel2.setText("NIM");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 451, 49, 14);

        jLabel3.setText("Email");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 476, 49, 14);

        jLabel4.setText("No. Telp");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(60, 501, 49, 14);

        jLabel5.setText("Alamat");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 524, 49, 14);

        FullName.setText("FullName");
        jPanel2.add(FullName);
        FullName.setBounds(183, 426, 153, 14);

        NIM.setText("NIM");
        jPanel2.add(NIM);
        NIM.setBounds(183, 451, 153, 14);

        Email.setText("Email");
        jPanel2.add(Email);
        Email.setBounds(183, 476, 153, 14);

        NoTelp.setText("No. Telp");
        jPanel2.add(NoTelp);
        NoTelp.setBounds(183, 501, 153, 14);

        Alamat.setText("Alamat");
        jPanel2.add(Alamat);
        Alamat.setBounds(183, 524, 153, 14);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Edit Profil");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        jPanel2.add(jLabel15);
        jLabel15.setBounds(289, 689, 61, 15);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 720, 360, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sipejalLogo.png"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 20, 230, 130);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 360, 750);

        MainPane.setBackground(new java.awt.Color(204, 204, 204));
        MainPane.setLayout(new java.awt.CardLayout());

        HomePane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("home");

        javax.swing.GroupLayout HomePaneLayout = new javax.swing.GroupLayout(HomePane);
        HomePane.setLayout(HomePaneLayout);
        HomePaneLayout.setHorizontalGroup(
            HomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePaneLayout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addComponent(jLabel11)
                .addContainerGap(540, Short.MAX_VALUE))
            .addComponent(jSeparator4)
        );
        HomePaneLayout.setVerticalGroup(
            HomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePaneLayout.createSequentialGroup()
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246)
                .addComponent(jLabel11)
                .addContainerGap(380, Short.MAX_VALUE))
        );

        MainPane.add(HomePane, "card2");

        PesanPane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("Pesan");

        javax.swing.GroupLayout PesanPaneLayout = new javax.swing.GroupLayout(PesanPane);
        PesanPane.setLayout(PesanPaneLayout);
        PesanPaneLayout.setHorizontalGroup(
            PesanPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesanPaneLayout.createSequentialGroup()
                .addContainerGap(602, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(379, 379, 379))
            .addComponent(jSeparator3)
        );
        PesanPaneLayout.setVerticalGroup(
            PesanPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesanPaneLayout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(jLabel12)
                .addContainerGap(464, Short.MAX_VALUE))
        );

        MainPane.add(PesanPane, "card3");

        KeranjangPane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("Keranjang");

        javax.swing.GroupLayout KeranjangPaneLayout = new javax.swing.GroupLayout(KeranjangPane);
        KeranjangPane.setLayout(KeranjangPaneLayout);
        KeranjangPaneLayout.setHorizontalGroup(
            KeranjangPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeranjangPaneLayout.createSequentialGroup()
                .addContainerGap(567, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(394, 394, 394))
            .addComponent(jSeparator2)
        );
        KeranjangPaneLayout.setVerticalGroup(
            KeranjangPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeranjangPaneLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(jLabel13)
                .addContainerGap(480, Short.MAX_VALUE))
        );

        MainPane.add(KeranjangPane, "card4");

        AboutUsPane.setBackground(new java.awt.Color(255, 255, 255));
        AboutUsPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutUsPaneMouseClicked(evt);
            }
        });

        jLabel14.setText("AboutUs");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout AboutUsPaneLayout = new javax.swing.GroupLayout(AboutUsPane);
        AboutUsPane.setLayout(AboutUsPaneLayout);
        AboutUsPaneLayout.setHorizontalGroup(
            AboutUsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutUsPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(360, 360, 360))
            .addGroup(AboutUsPaneLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(510, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        AboutUsPaneLayout.setVerticalGroup(
            AboutUsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutUsPaneLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(AboutUsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addContainerGap(460, Short.MAX_VALUE))
        );

        MainPane.add(AboutUsPane, "card5");

        getContentPane().add(MainPane);
        MainPane.setBounds(360, 100, 1010, 650);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        AboutUs.setBackground(new java.awt.Color(255, 255, 255));
        AboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutUsMouseEntered(evt);
            }
        });

        AboutUs1.setBackground(new java.awt.Color(255, 255, 255));
        AboutUs1.setPreferredSize(new java.awt.Dimension(150, 50));
        AboutUs1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutUs1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutUs1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutUs1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AboutUs1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AboutUs1MouseReleased(evt);
            }
        });

        AboutUsWord.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AboutUsWord.setText("About Us");

        javax.swing.GroupLayout AboutUs1Layout = new javax.swing.GroupLayout(AboutUs1);
        AboutUs1.setLayout(AboutUs1Layout);
        AboutUs1Layout.setHorizontalGroup(
            AboutUs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutUs1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(AboutUsWord)
                .addGap(45, 45, 45))
        );
        AboutUs1Layout.setVerticalGroup(
            AboutUs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutUs1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(AboutUsWord)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AboutUsLayout = new javax.swing.GroupLayout(AboutUs);
        AboutUs.setLayout(AboutUsLayout);
        AboutUsLayout.setHorizontalGroup(
            AboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutUsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AboutUs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        AboutUsLayout.setVerticalGroup(
            AboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutUsLayout.createSequentialGroup()
                .addComponent(AboutUs1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        Keranjang.setBackground(new java.awt.Color(255, 255, 255));
        Keranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KeranjangMouseClicked(evt);
            }
        });

        Keranjang1.setBackground(new java.awt.Color(255, 255, 255));
        Keranjang1.setPreferredSize(new java.awt.Dimension(150, 50));
        Keranjang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Keranjang1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Keranjang1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Keranjang1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Keranjang1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Keranjang1MouseReleased(evt);
            }
        });

        KeranjangWord.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        KeranjangWord.setText("Keranjang");

        javax.swing.GroupLayout Keranjang1Layout = new javax.swing.GroupLayout(Keranjang1);
        Keranjang1.setLayout(Keranjang1Layout);
        Keranjang1Layout.setHorizontalGroup(
            Keranjang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Keranjang1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(KeranjangWord)
                .addGap(43, 43, 43))
        );
        Keranjang1Layout.setVerticalGroup(
            Keranjang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Keranjang1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(KeranjangWord)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout KeranjangLayout = new javax.swing.GroupLayout(Keranjang);
        Keranjang.setLayout(KeranjangLayout);
        KeranjangLayout.setHorizontalGroup(
            KeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeranjangLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Keranjang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        KeranjangLayout.setVerticalGroup(
            KeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeranjangLayout.createSequentialGroup()
                .addComponent(Keranjang1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        Pesan.setBackground(new java.awt.Color(255, 255, 255));
        Pesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PesanMouseClicked(evt);
            }
        });

        Pesan1.setBackground(new java.awt.Color(255, 255, 255));
        Pesan1.setPreferredSize(new java.awt.Dimension(150, 50));
        Pesan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pesan1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pesan1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pesan1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pesan1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Pesan1MouseReleased(evt);
            }
        });

        PesanWord.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PesanWord.setText("Pesan");

        javax.swing.GroupLayout Pesan1Layout = new javax.swing.GroupLayout(Pesan1);
        Pesan1.setLayout(Pesan1Layout);
        Pesan1Layout.setHorizontalGroup(
            Pesan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pesan1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(PesanWord)
                .addGap(54, 54, 54))
        );
        Pesan1Layout.setVerticalGroup(
            Pesan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pesan1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(PesanWord)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout PesanLayout = new javax.swing.GroupLayout(Pesan);
        Pesan.setLayout(PesanLayout);
        PesanLayout.setHorizontalGroup(
            PesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Pesan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PesanLayout.setVerticalGroup(
            PesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesanLayout.createSequentialGroup()
                .addComponent(Pesan1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });

        Home1.setBackground(new java.awt.Color(255, 255, 255));
        Home1.setPreferredSize(new java.awt.Dimension(150, 50));
        Home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Home1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Home1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Home1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Home1MouseReleased(evt);
            }
        });

        HomeWord.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HomeWord.setText("Home");

        javax.swing.GroupLayout Home1Layout = new javax.swing.GroupLayout(Home1);
        Home1.setLayout(Home1Layout);
        Home1Layout.setHorizontalGroup(
            Home1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(HomeWord)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        Home1Layout.setVerticalGroup(
            Home1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Home1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomeWord)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addComponent(Home1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(400, Short.MAX_VALUE)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Pesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Keranjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Keranjang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AboutUs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pesan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(360, 0, 1010, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AboutUsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUsMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AboutUsMouseEntered

    private void AboutUs1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUs1MouseEntered
        // TODO add your handling code here:
        AboutUs1.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_AboutUs1MouseEntered

    private void AboutUs1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUs1MouseExited
        // TODO add your handling code here:
        AboutUs1.setBackground(Color.WHITE);
    }//GEN-LAST:event_AboutUs1MouseExited

    private void Keranjang1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Keranjang1MouseEntered
        // TODO add your handling code here:
        Keranjang1.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_Keranjang1MouseEntered

    private void Keranjang1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Keranjang1MouseExited
        // TODO add your handling code here:
        Keranjang1.setBackground(Color.WHITE);
    }//GEN-LAST:event_Keranjang1MouseExited

    private void Pesan1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pesan1MouseEntered
        // TODO add your handling code here:
        Pesan1.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_Pesan1MouseEntered

    private void Pesan1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pesan1MouseExited
        // TODO add your handling code here:
        Pesan1.setBackground(Color.WHITE);
    }//GEN-LAST:event_Pesan1MouseExited

    private void Home1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MouseEntered
        // TODO add your handling code here:
        Home1.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_Home1MouseEntered

    private void Home1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MouseExited
        // TODO add your handling code here:
        Home1.setBackground(Color.WHITE);
    }//GEN-LAST:event_Home1MouseExited

    private void AboutUsPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUsPaneMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AboutUsPaneMouseClicked

    private void KeranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeranjangMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_KeranjangMouseClicked

    private void PesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesanMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PesanMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HomeMouseClicked

    private void AboutUs1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUs1MouseClicked
        // TODO add your handling code here:
        AboutUsPane.setVisible(true);
        KeranjangPane.setVisible(false);
        PesanPane.setVisible(false);
        HomePane.setVisible(false);
        AboutUs.setBackground(new Color(0,153,0));
        Keranjang.setBackground(Color.white);
        Pesan.setBackground(Color.white);
        Home.setBackground(Color.white);
        HomeWord.setForeground(new Color(77, 77,77));
        PesanWord.setForeground(new Color(77, 77,77));
        KeranjangWord.setForeground(new Color(77, 77,77));
        AboutUsWord.setForeground(Color.black);
        
    }//GEN-LAST:event_AboutUs1MouseClicked

    private void Keranjang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Keranjang1MouseClicked
        // TODO add your handling code here:
        AboutUsPane.setVisible(false);
        KeranjangPane.setVisible(true);
        PesanPane.setVisible(false);
        HomePane.setVisible(false);
        AboutUs.setBackground(Color.white);
        Keranjang.setBackground(new Color(0,153,0));
        Pesan.setBackground(Color.white);
        Home.setBackground(Color.white);
        PageName = KeranjangWord.getText();
        HomeWord.setForeground(new Color(77, 77,77));
        PesanWord.setForeground(new Color(77, 77,77));
        KeranjangWord.setForeground(Color.black);
        AboutUsWord.setForeground(new Color(77, 77,77));
    }//GEN-LAST:event_Keranjang1MouseClicked

    private void Pesan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pesan1MouseClicked
        // TODO add your handling code here:
        AboutUsPane.setVisible(false);
        KeranjangPane.setVisible(false);
        PesanPane.setVisible(true);
        HomePane.setVisible(false);
        AboutUs.setBackground(Color.white);
        Keranjang.setBackground(Color.white);
        Pesan.setBackground(new Color(0,153,0));
        Home.setBackground(Color.white);
        HomeWord.setForeground(new Color(77, 77,77));
        PesanWord.setForeground(Color.BLACK);
        KeranjangWord.setForeground(new Color(77, 77,77));
        AboutUsWord.setForeground(new Color(77, 77,77));
        
        PageName = PesanWord.getText();
    }//GEN-LAST:event_Pesan1MouseClicked

    private void Home1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MouseClicked
        // TODO add your handling code here:
        AboutUsPane.setVisible(false);
        KeranjangPane.setVisible(false);
        PesanPane.setVisible(false);
        HomePane.setVisible(true);
        AboutUs.setBackground(Color.white);
        Keranjang.setBackground(Color.white);
        Pesan.setBackground(Color.white);
        Home.setBackground(new Color(0,153,0));
        HomeWord.setForeground(Color.black);
        PesanWord.setForeground(new Color(77, 77,77));
        KeranjangWord.setForeground(new Color(77, 77,77));
        AboutUsWord.setForeground(new Color(77, 77,77));
        PageName = "Home";
    }//GEN-LAST:event_Home1MouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        // TODO add your handling code here:
        jLabel15.setForeground(Color.blue);
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        // TODO add your handling code here:
        jLabel15.setForeground(Color.black);
    }//GEN-LAST:event_jLabel15MouseExited

    private void Home1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MousePressed
        // TODO add your handling code here:
        Home1.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_Home1MousePressed

    private void Home1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MouseReleased
        // TODO add your handling code here:
        Home1.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_Home1MouseReleased

    private void Pesan1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pesan1MousePressed
        // TODO add your handling code here:
        Pesan1.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_Pesan1MousePressed

    private void Pesan1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pesan1MouseReleased
        // TODO add your handling code here:
        Pesan1.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_Pesan1MouseReleased

    private void Keranjang1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Keranjang1MousePressed
        // TODO add your handling code here:
        Keranjang1.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_Keranjang1MousePressed

    private void Keranjang1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Keranjang1MouseReleased
        // TODO add your handling code here:
        Keranjang1.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_Keranjang1MouseReleased

    private void AboutUs1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUs1MousePressed
        // TODO add your handling code here:
        AboutUs1.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_AboutUs1MousePressed

    private void AboutUs1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUs1MouseReleased
        // TODO add your handling code here:
        AboutUs1.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_AboutUs1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutUs;
    private javax.swing.JPanel AboutUs1;
    private javax.swing.JPanel AboutUsPane;
    private javax.swing.JLabel AboutUsWord;
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel FullName;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Home1;
    private javax.swing.JPanel HomePane;
    private javax.swing.JLabel HomeWord;
    private javax.swing.JPanel Keranjang;
    private javax.swing.JPanel Keranjang1;
    private javax.swing.JPanel KeranjangPane;
    private javax.swing.JLabel KeranjangWord;
    private javax.swing.JPanel MainPane;
    private javax.swing.JLabel NIM;
    private javax.swing.JLabel NoTelp;
    private javax.swing.JPanel Pesan;
    private javax.swing.JPanel Pesan1;
    private javax.swing.JPanel PesanPane;
    private javax.swing.JLabel PesanWord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
