/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pesanjaketlab;

import java.awt.Color;

/**
 *
 * @author ILHAM HADISYAH
 */
public class ParentPage extends javax.swing.JFrame {

    /**
     * Creates new form ParentPage
     */
    public ParentPage() {
        initComponents();
        setLocationRelativeTo(this);
        setExtendedState(ParentPage.MAXIMIZED_BOTH);
        AboutUsPane.setVisible(false);
        KeranjangPane.setVisible(false);
        PesanPane.setVisible(false);
        HomePane.setVisible(true);
        AboutUs.setBackground(Color.white);
        Keranjang.setBackground(Color.white);
        Pesan.setBackground(Color.white);
        Home.setBackground(Color.GREEN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FullName = new javax.swing.JLabel();
        NIM = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        NoTelp = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        MainPane = new javax.swing.JPanel();
        HomePane = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        PesanPane = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        KeranjangPane = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        AboutUsPane = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        AboutUs = new javax.swing.JPanel();
        AboutUs1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Keranjang = new javax.swing.JPanel();
        Keranjang1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Pesan = new javax.swing.JPanel();
        Pesan1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        Home1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(128, 128, 128));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );

        jLabel1.setText("Full Name");

        jLabel2.setText("NIM");

        jLabel3.setText("Email");

        jLabel4.setText("No. Telp");

        jLabel5.setText("Alamat");

        FullName.setText("FullName");

        NIM.setText("NIM");

        Email.setText("Email");

        NoTelp.setText("No. Telp");

        Alamat.setText("Alamat");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Edit Profil");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FullName)
                            .addComponent(NIM)
                            .addComponent(Email)
                            .addComponent(NoTelp)
                            .addComponent(Alamat))))
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(74, 74, 74))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FullName))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NIM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NoTelp))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Alamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(66, 66, 66))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 410, 750);

        MainPane.setBackground(new java.awt.Color(204, 204, 204));
        MainPane.setLayout(new java.awt.CardLayout());

        jLabel11.setText("home");

        javax.swing.GroupLayout HomePaneLayout = new javax.swing.GroupLayout(HomePane);
        HomePane.setLayout(HomePaneLayout);
        HomePaneLayout.setHorizontalGroup(
            HomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePaneLayout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addComponent(jLabel11)
                .addContainerGap(490, Short.MAX_VALUE))
        );
        HomePaneLayout.setVerticalGroup(
            HomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePaneLayout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel11)
                .addContainerGap(380, Short.MAX_VALUE))
        );

        MainPane.add(HomePane, "card2");

        jLabel12.setText("Pesan");

        javax.swing.GroupLayout PesanPaneLayout = new javax.swing.GroupLayout(PesanPane);
        PesanPane.setLayout(PesanPaneLayout);
        PesanPaneLayout.setHorizontalGroup(
            PesanPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesanPaneLayout.createSequentialGroup()
                .addContainerGap(552, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(379, 379, 379))
        );
        PesanPaneLayout.setVerticalGroup(
            PesanPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesanPaneLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel12)
                .addContainerGap(464, Short.MAX_VALUE))
        );

        MainPane.add(PesanPane, "card3");

        jLabel13.setText("Keranjang");

        javax.swing.GroupLayout KeranjangPaneLayout = new javax.swing.GroupLayout(KeranjangPane);
        KeranjangPane.setLayout(KeranjangPaneLayout);
        KeranjangPaneLayout.setHorizontalGroup(
            KeranjangPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeranjangPaneLayout.createSequentialGroup()
                .addContainerGap(517, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(394, 394, 394))
        );
        KeranjangPaneLayout.setVerticalGroup(
            KeranjangPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeranjangPaneLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel13)
                .addContainerGap(480, Short.MAX_VALUE))
        );

        MainPane.add(KeranjangPane, "card4");

        AboutUsPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutUsPaneMouseClicked(evt);
            }
        });

        jLabel14.setText("AboutUs");

        javax.swing.GroupLayout AboutUsPaneLayout = new javax.swing.GroupLayout(AboutUsPane);
        AboutUsPane.setLayout(AboutUsPaneLayout);
        AboutUsPaneLayout.setHorizontalGroup(
            AboutUsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutUsPaneLayout.createSequentialGroup()
                .addContainerGap(559, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(360, 360, 360))
        );
        AboutUsPaneLayout.setVerticalGroup(
            AboutUsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutUsPaneLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel14)
                .addContainerGap(460, Short.MAX_VALUE))
        );

        MainPane.add(AboutUsPane, "card5");

        getContentPane().add(MainPane);
        MainPane.setBounds(410, 100, 960, 650);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        AboutUs.setBackground(new java.awt.Color(255, 255, 255));
        AboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutUsMouseEntered(evt);
            }
        });

        AboutUs1.setBackground(new java.awt.Color(255, 255, 255));
        AboutUs1.setPreferredSize(new java.awt.Dimension(150, 50));
        AboutUs1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutUs1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutUs1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutUs1MouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("About Us");

        javax.swing.GroupLayout AboutUs1Layout = new javax.swing.GroupLayout(AboutUs1);
        AboutUs1.setLayout(AboutUs1Layout);
        AboutUs1Layout.setHorizontalGroup(
            AboutUs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutUs1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(45, 45, 45))
        );
        AboutUs1Layout.setVerticalGroup(
            AboutUs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutUs1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AboutUsLayout = new javax.swing.GroupLayout(AboutUs);
        AboutUs.setLayout(AboutUsLayout);
        AboutUsLayout.setHorizontalGroup(
            AboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutUsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AboutUs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        AboutUsLayout.setVerticalGroup(
            AboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutUsLayout.createSequentialGroup()
                .addComponent(AboutUs1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        Keranjang.setBackground(new java.awt.Color(255, 255, 255));
        Keranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KeranjangMouseClicked(evt);
            }
        });

        Keranjang1.setBackground(new java.awt.Color(255, 255, 255));
        Keranjang1.setPreferredSize(new java.awt.Dimension(150, 50));
        Keranjang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Keranjang1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Keranjang1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Keranjang1MouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Keranjang");

        javax.swing.GroupLayout Keranjang1Layout = new javax.swing.GroupLayout(Keranjang1);
        Keranjang1.setLayout(Keranjang1Layout);
        Keranjang1Layout.setHorizontalGroup(
            Keranjang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Keranjang1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(43, 43, 43))
        );
        Keranjang1Layout.setVerticalGroup(
            Keranjang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Keranjang1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout KeranjangLayout = new javax.swing.GroupLayout(Keranjang);
        Keranjang.setLayout(KeranjangLayout);
        KeranjangLayout.setHorizontalGroup(
            KeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KeranjangLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Keranjang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        KeranjangLayout.setVerticalGroup(
            KeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeranjangLayout.createSequentialGroup()
                .addComponent(Keranjang1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        Pesan.setBackground(new java.awt.Color(255, 255, 255));
        Pesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PesanMouseClicked(evt);
            }
        });

        Pesan1.setBackground(new java.awt.Color(255, 255, 255));
        Pesan1.setPreferredSize(new java.awt.Dimension(150, 50));
        Pesan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pesan1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pesan1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pesan1MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Pesan");

        javax.swing.GroupLayout Pesan1Layout = new javax.swing.GroupLayout(Pesan1);
        Pesan1.setLayout(Pesan1Layout);
        Pesan1Layout.setHorizontalGroup(
            Pesan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pesan1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(54, 54, 54))
        );
        Pesan1Layout.setVerticalGroup(
            Pesan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pesan1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout PesanLayout = new javax.swing.GroupLayout(Pesan);
        Pesan.setLayout(PesanLayout);
        PesanLayout.setHorizontalGroup(
            PesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Pesan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PesanLayout.setVerticalGroup(
            PesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesanLayout.createSequentialGroup()
                .addComponent(Pesan1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });

        Home1.setBackground(new java.awt.Color(255, 255, 255));
        Home1.setPreferredSize(new java.awt.Dimension(150, 50));
        Home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Home1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Home1MouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Home");

        javax.swing.GroupLayout Home1Layout = new javax.swing.GroupLayout(Home1);
        Home1.setLayout(Home1Layout);
        Home1Layout.setHorizontalGroup(
            Home1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel10)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        Home1Layout.setVerticalGroup(
            Home1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Home1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addComponent(Home1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Pesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Keranjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Keranjang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AboutUs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pesan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(410, 0, 960, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AboutUsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUsMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AboutUsMouseEntered

    private void AboutUs1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUs1MouseEntered
        // TODO add your handling code here:
        AboutUs1.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_AboutUs1MouseEntered

    private void AboutUs1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUs1MouseExited
        // TODO add your handling code here:
        AboutUs1.setBackground(Color.WHITE);
    }//GEN-LAST:event_AboutUs1MouseExited

    private void Keranjang1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Keranjang1MouseEntered
        // TODO add your handling code here:
        Keranjang1.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_Keranjang1MouseEntered

    private void Keranjang1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Keranjang1MouseExited
        // TODO add your handling code here:
        Keranjang1.setBackground(Color.WHITE);
    }//GEN-LAST:event_Keranjang1MouseExited

    private void Pesan1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pesan1MouseEntered
        // TODO add your handling code here:
        Pesan1.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_Pesan1MouseEntered

    private void Pesan1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pesan1MouseExited
        // TODO add your handling code here:
        Pesan1.setBackground(Color.WHITE);
    }//GEN-LAST:event_Pesan1MouseExited

    private void Home1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MouseEntered
        // TODO add your handling code here:
        Home1.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_Home1MouseEntered

    private void Home1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MouseExited
        // TODO add your handling code here:
        Home1.setBackground(Color.WHITE);
    }//GEN-LAST:event_Home1MouseExited

    private void AboutUsPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUsPaneMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AboutUsPaneMouseClicked

    private void KeranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeranjangMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_KeranjangMouseClicked

    private void PesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesanMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PesanMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HomeMouseClicked

    private void AboutUs1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUs1MouseClicked
        // TODO add your handling code here:
        AboutUsPane.setVisible(true);
        KeranjangPane.setVisible(false);
        PesanPane.setVisible(false);
        HomePane.setVisible(false);
        AboutUs.setBackground(new Color(0,153,0));
        Keranjang.setBackground(Color.white);
        Pesan.setBackground(Color.white);
        Home.setBackground(Color.white);
    }//GEN-LAST:event_AboutUs1MouseClicked

    private void Keranjang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Keranjang1MouseClicked
        // TODO add your handling code here:
        AboutUsPane.setVisible(false);
        KeranjangPane.setVisible(true);
        PesanPane.setVisible(false);
        HomePane.setVisible(false);
        AboutUs.setBackground(Color.white);
        Keranjang.setBackground(new Color(0,153,0));
        Pesan.setBackground(Color.white);
        Home.setBackground(Color.white);
    }//GEN-LAST:event_Keranjang1MouseClicked

    private void Pesan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pesan1MouseClicked
        // TODO add your handling code here:
        AboutUsPane.setVisible(false);
        KeranjangPane.setVisible(false);
        PesanPane.setVisible(true);
        HomePane.setVisible(false);
        AboutUs.setBackground(Color.white);
        Keranjang.setBackground(Color.white);
        Pesan.setBackground(new Color(0,153,0));
        Home.setBackground(Color.white);
    }//GEN-LAST:event_Pesan1MouseClicked

    private void Home1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MouseClicked
        // TODO add your handling code here:
        AboutUsPane.setVisible(false);
        KeranjangPane.setVisible(false);
        PesanPane.setVisible(false);
        HomePane.setVisible(true);
        AboutUs.setBackground(Color.white);
        Keranjang.setBackground(Color.white);
        Pesan.setBackground(Color.white);
        Home.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_Home1MouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        // TODO add your handling code here:
        jLabel15.setForeground(Color.blue);
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        // TODO add your handling code here:
        jLabel15.setForeground(Color.black);
    }//GEN-LAST:event_jLabel15MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutUs;
    private javax.swing.JPanel AboutUs1;
    private javax.swing.JPanel AboutUsPane;
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel FullName;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Home1;
    private javax.swing.JPanel HomePane;
    private javax.swing.JPanel Keranjang;
    private javax.swing.JPanel Keranjang1;
    private javax.swing.JPanel KeranjangPane;
    private javax.swing.JPanel MainPane;
    private javax.swing.JLabel NIM;
    private javax.swing.JLabel NoTelp;
    private javax.swing.JPanel Pesan;
    private javax.swing.JPanel Pesan1;
    private javax.swing.JPanel PesanPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
